from __future__ import annotations

import json
from collections import deque
from typing import Any

from sequence.agent.helpers.tool_helper import ToolHelper
from sequence.models.workspace import WorkspaceNodeType

_MAX_FOLDER_FILES = 100
_MAX_FILE_CONTENT_CHARS = 20_000


async def read_file(
    path: str,
    tool_helper: ToolHelper = None,
) -> str:
    """
    Read a text file from the authenticated user's workspace.

    Args:
        path: Absolute workspace file path to read (e.g. "/notes/todo.md").
    """
    try:
        if tool_helper is None:
            return json.dumps({"error": "Missing tool helper dependency"})

        user_id, workspace_service = tool_helper.require_workspace_context()
        file_entry = await workspace_service.read_file(user_id=user_id, path=path)
        payload = file_entry.model_dump(mode="json")

        content = payload.get("content")
        if isinstance(content, str) and len(content) > _MAX_FILE_CONTENT_CHARS:
            payload["content"] = content[:_MAX_FILE_CONTENT_CHARS]
            payload["content_truncated"] = True
            payload["content_original_length"] = len(content)

        return json.dumps(payload, default=str)
    except Exception as exc:
        return json.dumps({"error": str(exc) or "Failed to read file"})


async def read_folder(
    path: str,
    recursive: bool = False,
    max_files: int = 50,
    tool_helper: ToolHelper = None,
) -> str:
    """
    Read files from a workspace folder.

    Args:
        path: Absolute workspace folder path to read (e.g. "/src").
        recursive: When true, include files from nested folders.
        max_files: Maximum number of files to return (clamped to 1-100).
    """
    try:
        if tool_helper is None:
            return json.dumps({"error": "Missing tool helper dependency"})

        user_id, workspace_service = tool_helper.require_workspace_context()
        capped_max_files = max(1, min(int(max_files), _MAX_FOLDER_FILES))

        queue: deque[str] = deque([path])
        files: list[dict[str, Any]] = []

        while queue and len(files) < capped_max_files:
            current_folder = queue.popleft()
            listing = await workspace_service.list_directory_children(
                user_id=user_id,
                path=current_folder,
            )

            for child in listing.children:
                if child.node_type == WorkspaceNodeType.FOLDER:
                    if recursive:
                        queue.append(child.path)
                    continue

                file_entry = await workspace_service.read_file(user_id=user_id, path=child.path)
                payload = file_entry.model_dump(mode="json")
                content = payload.get("content")
                if isinstance(content, str) and len(content) > _MAX_FILE_CONTENT_CHARS:
                    payload["content"] = content[:_MAX_FILE_CONTENT_CHARS]
                    payload["content_truncated"] = True
                    payload["content_original_length"] = len(content)

                files.append(payload)
                if len(files) >= capped_max_files:
                    break

        result = {
            "path": path,
            "recursive": recursive,
            "max_files": capped_max_files,
            "returned_files": len(files),
            "truncated": len(files) >= capped_max_files,
            "files": files,
        }
        return json.dumps(result, default=str)
    except Exception as exc:
        return json.dumps({"error": str(exc) or "Failed to read folder"})


async def list_directory(
    path: str = "/",
    tool_helper: ToolHelper = None,
) -> str:
    """
    List direct children of a workspace folder.

    Args:
        path: Absolute workspace folder path to list (defaults to root "/").
    """
    try:
        if tool_helper is None:
            return json.dumps({"error": "Missing tool helper dependency"})

        user_id, workspace_service = tool_helper.require_workspace_context()
        listing = await workspace_service.list_directory_children(user_id=user_id, path=path)
        return json.dumps(listing.model_dump(mode="json"), default=str)
    except Exception as exc:
        return json.dumps({"error": str(exc) or "Failed to list directory"})


async def write_file(
    path: str,
    content: str,
    overwrite: bool = True,
    tool_helper: ToolHelper = None,
) -> str:
    """
    Create or update a text file in the authenticated user's workspace.
    When writing Python files, use print() for any output you need to see — stdout is the only channel back to you after execution.
    Scripts run in an isolated temp directory, so any files created during execution are discarded. Do not rely on files generated by executed scripts; only print() output is accessible.

    Args:
        path: Absolute workspace file path to write (e.g. "/src/app.py").
        content: UTF-8 text content to store in the file.
        overwrite: When false, fail if the target file already exists.
    """
    try:
        if tool_helper is None:
            return json.dumps({"error": "Missing tool helper dependency"})

        user_id, workspace_service = tool_helper.require_workspace_context()

        if not overwrite:
            try:
                await workspace_service.read_file(user_id=user_id, path=path)
                return json.dumps({"error": f"File already exists: {path}"})
            except FileNotFoundError:
                pass

        result = await workspace_service.write_text_file(
            user_id=user_id,
            path=path,
            content=content,
        )
        return json.dumps(result.model_dump(mode="json"), default=str)
    except Exception as exc:
        return json.dumps({"error": str(exc) or "Failed to write file"})


async def edit_file(
    path: str,
    old_text: str,
    new_text: str,
    replace_all: bool = False,
    tool_helper: ToolHelper = None,
) -> str:
    """
    Edit an existing text file by replacing text content.

    Args:
        path: Absolute workspace file path to edit (e.g. "/src/app.py").
        old_text: The exact text to find in the file.
        new_text: The replacement text.
        replace_all: When true, replace every occurrence. When false, replace only the first occurrence.
    """
    try:
        if tool_helper is None:
            return json.dumps({"error": "Missing tool helper dependency"})
        if not isinstance(old_text, str) or old_text == "":
            return json.dumps({"error": "old_text must be a non-empty string"})

        user_id, workspace_service = tool_helper.require_workspace_context()
        file_entry = await workspace_service.read_file(user_id=user_id, path=path)

        content = file_entry.content
        if not isinstance(content, str):
            return json.dumps({"error": f"Workspace file is not valid UTF-8 text: {path}"})

        total_matches = content.count(old_text)
        if total_matches == 0:
            return json.dumps({"error": f"Text not found in file: {path}"})

        updated_content = content.replace(old_text, new_text) if replace_all else content.replace(old_text, new_text, 1)
        replacements = total_matches if replace_all else 1

        if updated_content == content:
            return json.dumps(
                {
                    "path": file_entry.path,
                    "edited": False,
                    "replacements": 0,
                    "message": "No changes were written because old_text and new_text are identical.",
                }
            )

        result = await workspace_service.write_text_file(
            user_id=user_id,
            path=file_entry.path,
            content=updated_content,
        )
        payload = result.model_dump(mode="json")
        payload["edited"] = True
        payload["replacements"] = replacements
        payload["replace_all"] = bool(replace_all)
        return json.dumps(payload, default=str)
    except Exception as exc:
        return json.dumps({"error": str(exc) or "Failed to edit file"})


async def create_folder(
    path: str,
    recursive: bool = True,
    tool_helper: ToolHelper = None,
) -> str:
    """
    Create a folder in the authenticated user's workspace.

    Args:
        path: Absolute workspace folder path to create (e.g. "/src/utils").
        recursive: When true, create missing parent folders as needed.
    """
    try:
        if tool_helper is None:
            return json.dumps({"error": "Missing tool helper dependency"})

        user_id, workspace_service = tool_helper.require_workspace_context()
        result = await workspace_service.create_folder(
            user_id=user_id,
            path=path,
            recursive=recursive,
        )
        return json.dumps(result.model_dump(mode="json"), default=str)
    except Exception as exc:
        return json.dumps({"error": str(exc) or "Failed to create folder"})


async def delete_file(
    path: str,
    tool_helper: ToolHelper = None,
) -> str:
    """
    Delete a file from the authenticated user's workspace.

    Args:
        path: Absolute workspace file path to delete.
    """
    try:
        if tool_helper is None:
            return json.dumps({"error": "Missing tool helper dependency"})

        user_id, workspace_service = tool_helper.require_workspace_context()
        result = await workspace_service.delete_file(user_id=user_id, path=path)
        return json.dumps(result.model_dump(mode="json"), default=str)
    except Exception as exc:
        return json.dumps({"error": str(exc) or "Failed to delete file"})


async def delete_folder(
    path: str,
    recursive: bool = False,
    tool_helper: ToolHelper = None,
) -> str:
    """
    Delete a folder from the authenticated user's workspace.

    Args:
        path: Absolute workspace folder path to delete.
        recursive: When true, delete nested children as part of the operation.
    """
    try:
        if tool_helper is None:
            return json.dumps({"error": "Missing tool helper dependency"})

        user_id, workspace_service = tool_helper.require_workspace_context()
        result = await workspace_service.delete_folder(
            user_id=user_id,
            path=path,
            recursive=recursive,
        )
        return json.dumps(result.model_dump(mode="json"), default=str)
    except Exception as exc:
        return json.dumps({"error": str(exc) or "Failed to delete folder"})
