import json
import sys
import tempfile
from pathlib import Path
import asyncio

from sequence.models.workspace import WorkspaceNodeType
from sequence.agent.helpers.tool_helper import ToolHelper


_PYTHON_EXEC_TIMEOUT_SECONDS = 30
_MAX_EXEC_OUTPUT_CHARS = 20_000
_MAX_EXEC_CONTEXT_FILES = 200
_MAX_EXEC_CONTEXT_BYTES = 5_000_000




async def execute_python_file(
    path: str,
    tool_helper: ToolHelper = None,
) -> str:
    """
    Execute a Python file from the authenticated user's workspace and return its stdout.
    The script runs in an isolated temp directory — any files it creates are discarded after execution.
    You will NOT have access to files generated by the script. Use print() statements to capture all results you need.

    Args:
        path: Absolute workspace path to a `.py` file (for example "/scripts/task.py").
    """
    def _truncate_text(text: str, *, limit: int) -> tuple[str, bool]:
        if len(text) <= limit:
            return text, False
        return text[:limit], True

    try:
        if tool_helper is None:
            return json.dumps({"error": "Missing tool helper dependency"})

        if not isinstance(path, str) or not path.strip():
            return json.dumps({"error": "Path is required"})
        if not path.lower().endswith(".py"):
            return json.dumps({"error": f"Only .py files are supported: {path}"})

        user_id, workspace_service = tool_helper.require_workspace_context()
        normalized_path = workspace_service.normalize_absolute_path(path)
        if normalized_path == "/":
            return json.dumps({"error": "Path must point to a file, not root"})

        script_parent = normalized_path.rsplit("/", 1)[0] or "/"

        listing = await workspace_service.list_directory_children(user_id=user_id, path=script_parent)
        sibling_files = [child for child in listing.children if child.node_type == WorkspaceNodeType.FILE]
        if len(sibling_files) > _MAX_EXEC_CONTEXT_FILES:
            return json.dumps(
                {
                    "error": (
                        f"Folder has too many files to execute safely: "
                        f"{len(sibling_files)} > {_MAX_EXEC_CONTEXT_FILES}"
                    )
                }
            )

        with tempfile.TemporaryDirectory(prefix="sequence-agent-python-") as tmpdir:
            total_bytes = 0
            for file_node in sibling_files:
                file_entry = await workspace_service.read_file(user_id=user_id, path=file_node.path)
                file_content = file_entry.content
                if not isinstance(file_content, str):
                    return json.dumps({"error": f"Workspace file is not valid UTF-8 text: {file_node.path}"})

                encoded = file_content.encode("utf-8")
                total_bytes += len(encoded)
                if total_bytes > _MAX_EXEC_CONTEXT_BYTES:
                    return json.dumps(
                        {
                            "error": (
                                "Folder content is too large to execute safely: "
                                f"{total_bytes} > {_MAX_EXEC_CONTEXT_BYTES} bytes"
                            )
                        }
                    )

                local_file_path = Path(tmpdir) / file_node.name
                local_file_path.write_text(file_content, encoding="utf-8")

            target_path = Path(tmpdir) / Path(normalized_path).name
            if not target_path.exists():
                return json.dumps({"error": f"File not found in workspace folder listing: {normalized_path}"})

            process = await asyncio.create_subprocess_exec(
                sys.executable,
                str(target_path),
                cwd=tmpdir,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )

            timed_out = False
            try:
                stdout_bytes, stderr_bytes = await asyncio.wait_for(
                    process.communicate(),
                    timeout=_PYTHON_EXEC_TIMEOUT_SECONDS,
                )
            except asyncio.TimeoutError:
                timed_out = True
                process.kill()
                stdout_bytes, stderr_bytes = await process.communicate()

            stdout_text = stdout_bytes.decode("utf-8", errors="replace")
            stderr_text = stderr_bytes.decode("utf-8", errors="replace")
            stdout_text, _ = _truncate_text(stdout_text, limit=_MAX_EXEC_OUTPUT_CHARS)
            stderr_text, _ = _truncate_text(stderr_text, limit=_MAX_EXEC_OUTPUT_CHARS)

            if timed_out:
                return f"Execution timed out after {_PYTHON_EXEC_TIMEOUT_SECONDS}s."
            if process.returncode != 0:
                return stderr_text or f"Python exited with code {process.returncode}."

            return stdout_text
    except Exception as exc:
        return json.dumps({"error": str(exc) or "Failed to execute Python file"})
